In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris(as_frame=True)
X = iris['data']
y = iris['target']

In [3]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [5]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=99)

In [11]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
112                6.8               3.0                5.5               2.1
97                 6.2               2.9                4.3               1.3
86                 6.7               3.1                4.7               1.5
67                 5.8               2.7                4.1               1.0
126                6.2               2.8                4.8               1.8
..                 ...               ...                ...               ...
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8
68                 6.2               2.2                4.5               1.5
35                 5.0               3.2                1.2               0.2
129                7.2               3.0                5.8               1.6

[112 rows x 4 columns]

In [12]:
y_train

112    2
97     1
86     1
67     1
126    2
      ..
148    2
149    2
68     1
35     0
129    2
Name: target, Length: 112, dtype: int32

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
X_test = scaler.fit_transform(X_test)
X_train = scaler.fit_transform(X_train)

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array([2, 0, 1, 2, 0, 1, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 0, 1, 1, 0, 0, 2])

In [17]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

In [18]:
print(accuracy_score(y_test,y_pred))

0.9473684210526315


In [19]:
print(precision_score(y_test,y_pred,average='macro')) 

0.9484126984126985


In [20]:
print(recall_score(y_test,y_pred,average='macro'))

0.9484126984126985


In [21]:
print(confusion_matrix(y_test,y_pred))

[[12  0  0]
 [ 0 13  1]
 [ 0  1 11]]


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.93      0.93      0.93        14
           2       0.92      0.92      0.92        12

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



In [23]:
new_data = [[5.0,3.2,1.2,0.2],[6.2,2.9,4.3,1.3],[6.8,3.0,5.5,2.1]]

In [24]:
std = StandardScaler()

In [25]:
new_data = std.fit_transform(new_data)

In [26]:
new_data

array([[-1.33630621,  1.33630621, -1.36152768, -1.28388148],
       [ 0.26726124, -1.06904497,  0.34958143,  0.12838815],
       [ 1.06904497, -0.26726124,  1.01194625,  1.15549333]])

In [27]:
new_pred = model.predict(new_data)

In [28]:
new_pred

array([0, 1, 2])